name: model-training
on: [push]
jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install opencv-contrib-python
          pip install -r requirements.txt
          python AgeGenderAPI.py 
          
          echo "## Model metrics" 
          cat results.txt >> report.md
          cml send-comment report.md
          

          
