name: CML
on: [push]
jobs:
  run:
    runs-on: windows-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install opencv-contrib-python
          pip install -r requirements.txt
          python AgeGenderAPI.py 

          cat results.txt >> report.md
          cml-send-comment report.md
          

          
